document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width initial-scale=1\'>");
document.writeln("    <link rel=\"stylesheet\" href=\"https://www.qin-juan-ge-zhu.top/common/CSS/MySet.css\">");
document.writeln("    <script src=\"https://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js\"></script>");
document.writeln("    <script type=\"text/javascript\" src=\"https://www.qin-juan-ge-zhu.top/common/js/click4code.js\"></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body class=\'typora-export os-windows\'>");
document.writeln("    <div class=\"yanhua\"></div>");
document.writeln("    <div class=\"sidebar\" name=\"sizebar\">");
document.writeln("        <img name=\"room\" src=\"https://www.qin-juan-ge-zhu.top/common/room.png \" alt=\"勤倦阁\" width=\"280\" usemap=\"#room\">");
document.writeln("        <map name=\"room\">");
document.writeln("            <area shape=\"rect\" coords=\"192,32,207,50\" href=\"https://www.qin-juan-ge-zhu.top/SecretNotes\">");
document.writeln("            <area shape=\"rect\" coords=\"27,27,192,96\" href=\"https://www.qin-juan-ge-zhu.top\">");
document.writeln("            <area shape=\"rect\" coords=\"192,27,207,32\" href=\"https://www.qin-juan-ge-zhu.top\">");
document.writeln("            <area shape=\"rect\" coords=\"192,50,207,96\" href=\"https://www.qin-juan-ge-zhu.top\">");
document.writeln("            <area shape=\"rect\" coords=\"207,27,247,96\" href=\"https://www.qin-juan-ge-zhu.top\">");
document.writeln("        </map>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
